version: '3'
services:
  teletrans:
    container_name: teletrans
    build: .
    image: teletrans:local
    restart: unless-stopped
    volumes:
      - .:/app/config
    environment:
      - DEEPL_AUTH_KEY=${DEEPL_AUTH_KEY-}

